- hosts: localhost
  user: vagrant
  tasks:
    - name: apt update
      become: yes
      apt:
        name: "*"
        state: latest
    - name: install git
      become: yes
      apt:
        name: git
        state: latest
    - name: apt add repository brightbox/ruby-ng
      become: yes
      apt_repository:
        repo: ppa:brightbox/ruby-ng
    - name: apt update
      become: yes
      apt:
        name: "*"
        state: latest
    - name: install ruby v2.5.x
      become: yes
      apt:
        name: ruby2.5
        state: latest
    - name: prepare for install rails
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - ruby2.5-dev
        - ruby-switch
        - libxml2
        - libxml2-dev
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
        - ruby-railties
        - nodejs
    - name: switch ruby-2.5
      shell: sudo ruby-switch --set ruby2.5
    - name: install bundler
      gem:
        name: bundler
        user_install: no
    - name: install rails
      gem:
        name: rails
        user_install: no
    - name: install libmysqlclient-dev
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - libmysqlclient-dev
        - mysql-client-core-5.6
    - name: install docker
      shell: | 
        curl -fsSL get.docker.com -o get-docker.sh
        sh get-docker.sh
        rm get-docker.sh
    - name: adding user vagrant docker
      become: yes
      user:
        name: vagrant
        group: docker
        append: yes
