- hosts: localhost
  user: vagrant
  tasks:
    - name: install aptitude
      apt:
        name: aptitude
        state: latest
    - name: apt update
      become: yes
      apt:
        name: "*"
        state: latest
    - name: install git
      become: yes
      apt:
        name: git
        state: latest
    - name: apt add repository brightbox/ruby-ng
      become: yes
      apt_repository:
        repo: ppa:brightbox/ruby-ng
    - name: apt update
      become: yes
      apt:
        name: "*"
        state: latest
    - name: install ruby v2.5.x
      become: yes
      apt:
        name: ruby2.5
        state: latest
    - name: prepare for install rails
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - ruby2.5-dev
        - ruby-switch
        - libxml2
        - libxml2-dev
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
        - ruby-railties
        - nodejs
        - gcc
        - make
        - zlib1g-dev
        - sqlite3
    - name: switch ruby-2.5
      command: sudo ruby-switch --set ruby2.5
      changed_when: false
    - name: install bundler
      gem:
        name: bundler
        user_install: no
    - name: install rails
      gem:
        name: rails
        user_install: no
    - name: install libmysqlclient-dev
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - libmysqlclient-dev
        - mysql-client-core-5.7
    - name: check docker
      command: sudo docker ps
      register: docker_result
      changed_when: false
      failed_when: false
    - name: install docker
      shell: | 
        curl -fsSL get.docker.com -o get-docker.sh
        sh get-docker.sh
        rm get-docker.sh
      when:
        docker_result.rc != 0
    - name: adding user vagrant docker
      become: yes
      user:
        name: vagrant
        group: docker
        append: yes
