- hosts: localhost
  user: root
  tasks:
    - name: apt update
      apt: name=* state=latest
    - name: install git
      apt: name=git state=latest
    - git: repo=https://github.com/sstephenson/rbenv.git dest=/root/.rbenv version=master
    - name: install rbenv
      lineinfile:
        dest=/root/.bashrc
        line={{ item }}
      with_items:
        - 'export PATH="$HOME/.rbenv/bin:$PATH"'
        - 'eval "$(rbenv init -)"'
    - name: install ruby-build
      shell: git clone https://github.com/sstephenson/ruby-build.git /root/.rbenv/plugins/ruby-build
    - name: install ruby v2.5.0
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
    - shell: /root/.rbenv/bin/rbenv install 2.5.0
    - shell: /root/.rbenv/bin/rbenv global 2.5.0
    - name: install rails
      shell: gem install rails
    - name: install docker
      shell: curl -fsSL get.docker.com -o get-docker.sh
    - shell: sh get-docker.sh
    - shell: rm get-docker.sh
