- hosts: localhost
  user: vagrant
  tasks:
    - name: apt update
      become: yes
      apt:
        name: "*"
        state: latest
    - name: install git
      become: yes
      apt:
        name: git
        state: latest
    - git:
        repo: https://github.com/sstephenson/rbenv.git
        dest: /home/vagrant/.rbenv
        version: master
    - file:
       path: /home/vagrant/.bash_profile
       state: touch
    - name: install rbenv
      lineinfile:
        dest: /home/vagrant/.bash_profile
        line: "{{ item }}"
      with_items:
        - 'export PATH="$HOME/.rbenv/bin:$PATH"'
        - 'eval "$(rbenv init -)"'
    - name: install ruby-build
      git:
        repo: https://github.com/sstephenson/ruby-build.git
        dest: /home/vagrant/.rbenv/plugins/ruby-build
    - name: install ruby v2.5.0
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
    - shell: |
        sudo ~/.rbenv/bin/rbenv install 2.5.0
        sudo ~/.rbenv/bin/rbenv global 2.5.0
    - name: install bundler
      gem:
        name: bundler
        user_install: no
        executable: ~/.rbenv/shims/gem
    - name: install rails
      gem:
        name: rails
        user_install: no
        executable: ~/.rbenv/shims/gem
    - name: install docker
      shell: | 
        curl -fsSL get.docker.com -o get-docker.sh
        sh get-docker.sh
        rm get-docker.sh
